import { notFound } from "next/navigation";
import Link from "next/link";
import { BLOG_POSTS } from "@/lib/blogData";
import { Calendar, Clock, ArrowLeft, ArrowRight, Wand2 } from "lucide-react";

interface BlogPostPageProps {
  params: {
    slug: string;
  };
}

export function generateStaticParams() {
  return BLOG_POSTS.map((post) => ({
    slug: post.slug,
  }));
}

export function generateMetadata({ params }: BlogPostPageProps) {
  const post = BLOG_POSTS.find((p) => p.slug === params.slug);
  if (!post) return {};
  return {
    title: `${post.title} — Swift AI Humanizer Blog`,
    description: post.excerpt,
  };
}

export default function BlogPostPage({ params }: BlogPostPageProps) {
  const post = BLOG_POSTS.find((p) => p.slug === params.slug);

  if (!post) {
    notFound();
  }

  return (
    <article className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-16 space-y-8 font-sans">
      <Link
        href="/blog"
        className="inline-flex items-center gap-1.5 text-xs font-semibold text-slate-500 hover:text-brand-600 dark:hover:text-emerald-400 transition-colors"
      >
        <ArrowLeft className="w-3.5 h-3.5" />
        <span>Back to Blog</span>
      </Link>

      <div className="space-y-4 border-b border-slate-200 dark:border-slate-800 pb-8">
        <div className="flex items-center gap-4 text-xs text-slate-400 font-mono">
          <span className="flex items-center gap-1">
            <Calendar className="w-3.5 h-3.5" />
            {post.date}
          </span>
          <span className="flex items-center gap-1">
            <Clock className="w-3.5 h-3.5" />
            {post.readTime}
          </span>
        </div>

        <h1 className="font-heading font-extrabold text-3xl sm:text-4xl text-slate-900 dark:text-white leading-tight">
          {post.title}
        </h1>
      </div>

      <div className="prose prose-slate dark:prose-invert max-w-none text-sm leading-relaxed space-y-6">
        <p className="text-base text-slate-700 dark:text-slate-200 font-medium leading-relaxed">
          {post.excerpt}
        </p>

        <div className="space-y-4 pt-4">
          <h2 className="font-heading font-bold text-xl text-slate-900 dark:text-white">
            Key Insights
          </h2>
          <p>
            AI detection tools operate by analyzing statistical entropy in text sequences. When writing is generated by LLMs like ChatGPT or Claude, sentence structures tend to be highly uniform, leading to low burstiness scores and predictable word pairings.
          </p>
          <p>
            Swift AI Humanizer automatically handles burstiness, vocabulary entropy, and contraction injection in seconds.
          </p>
        </div>
      </div>

      <div className="bg-gradient-to-r from-brand-600 to-brand-800 rounded-3xl p-8 text-center text-white space-y-4 shadow-lg mt-12">
        <h3 className="font-heading font-extrabold text-xl">
          Humanize Your AI Drafts Free
        </h3>
        <p className="text-xs opacity-90 max-w-md mx-auto">
          Pass Turnitin and GPTZero with zero sign-up required.
        </p>
        <Link
          href="/#humanizer"
          className="inline-flex items-center gap-2 px-6 py-3 rounded-full font-heading font-bold text-xs text-brand-900 bg-white hover:bg-slate-50 transition-all hover:scale-105"
        >
          <span>Try Swift AI Humanizer</span>
          <ArrowRight className="w-4 h-4" />
        </Link>
      </div>
    </article>
  );
}
